#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent

timezone: Asia/Manila
users:
  - name: ubuntu
    passwd: Alger_143
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAmfaZrfrhdh/pgFtuqeF0SFlTajOfmzFrCsDYy5RAb PC@Bert-PC

power_state:
    delay: now
    mode: reboot
    message: Rebooting after cloud-init completion
    condition: true